USE [master]
GO

/****** Object:  Database [AutoclimaRepair]    Script Date: 23/07/2023 16:08:15 ******/
CREATE DATABASE [AutoclimaRepair]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AutoclimaRepair', FILENAME = N'D:\Applicazioni\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AutoclimaRepair.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AutoclimaRepair_log', FILENAME = N'D:\Applicazioni\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AutoclimaRepair_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutoclimaRepair].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AutoclimaRepair] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET ARITHABORT OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AutoclimaRepair] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AutoclimaRepair] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AutoclimaRepair] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AutoclimaRepair] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET RECOVERY FULL 
GO

ALTER DATABASE [AutoclimaRepair] SET  MULTI_USER 
GO

ALTER DATABASE [AutoclimaRepair] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AutoclimaRepair] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AutoclimaRepair] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AutoclimaRepair] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AutoclimaRepair] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AutoclimaRepair] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AutoclimaRepair] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AutoclimaRepair] SET  READ_WRITE 
GO


